name: phy
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - scipy
  - h5py
  - cython
  - pyside6
  - pip:
    - klusta
    - klustakwik2
    - vispy
    - requests
    - traitlets
    - joblib
    - click
    - tqdm
